#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
hrs=0
while ((hrs <= 12)); do
	echo "Hour: $hrs"
	min=1
	while ((min <= 59)); do
		echo "$min"
		((min++))
	done
	((hrs++))
done
