#!/usr/bin/env bash
# a Bash script that displays:The content of the current directory, In a list format, Where only the part of the name after the first dash is displayed
for i in $(find . -maxdepth 1 -type f -exec basename {} \; | cut -d '-' -f 2-); do
	echo "$i"
done
